spring.application.name=biblioteca

#CONFIGURACIÓN BASE DE DATOS
spring.datasource.url = ${DATA_BASE_URL}
spring.datasource.username = ${DATA_BASE_USER}
spring.datasource.password = ${DATA_BASE_PASSWORD}

#CONFIGURACIÓN JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#CONFIGURACION DOCUMENTACION SWAGGER
springdoc.swagger-ui.path=/api-documentacion
springdoc.api-docs.path=/api-docs

#APP CONFIGURACIÓN
app.prestamo-dias-limite = 15
app.multa-costo-por-dia = 25
app.upload.dir = uploads
app.admin.contrasena = AdminSuper26
app.admin.correo = superAdmin@me.com

#CONFIGURACIÓN JWT SEGURIDAD
# 2 HORAS
jwt.expirate.access= ${JWT_EXPIRATE_ACCESS_TOKEN}

# 1 dia
jwt.expirate.refesh= ${JWT_EXPIRATE_REFRESH_TOKEN}

# Clave secreta para firmar
jwt.secret = ${JWT_SECRET_KEY}
